- hosts: kube-node
  roles:
    - { role: kube-node, when: "DEPLOY_MODE != 'allinone'" }

- hosts:
    - kube-master
    - kube-node
  roles:
    - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
    - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
    - coredns

