---
- name: remove packages
  yum:
    name:
      - nvidia-docker
      - nvidia-docker2
    state: absent
    autoremove: yes

- name: add repo
  get_url:
    url: "{{ nvidia_docker_repo_base_url }}/{{ _rhel_repo_dist_name }}/{{ _rhel_repo_file_name }}"
    dest: "{{ _rhel_repo_file_path }}"
    mode: 0644
    owner: root
    group: root
  when: nvidia_docker_add_repo

- name: install packages
  yum:
    name: nvidia-container-runtime
    state: present
    update_cache: yes

- name: set docker daemon configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: reload docker
  service:
    name: docker
    state: reloaded

- name: grab nvidia-docker wrapper
  copy:
    src: nvidia-docker
    dest: /usr/local/bin/nvidia-docker
    mode: 0755
    owner: root
    group: root