_rhel_repo_dist_name: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}"
_rhel_repo_file_name: "nvidia-docker.repo"
_rhel_repo_file_path: "/etc/yum.repos.d/{{ _rhel_repo_file_name }}"

nvidia_container_runtime_package_version: ''
docker_daemon_json:
  runtimes:
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []
  default-runtime: nvidia
  default-shm-size: 1G
  default-ulimits:
    memlock:
      name: memlock
      hard: -1
      soft: -1
    stack:
      name: stack
      hard: 67108864
      soft: 67108864

nvidia_docker_repo_base_url: "https://nvidia.github.io/nvidia-docker"
nvidia_docker_repo_gpg_url: "{{ nvidia_docker_repo_base_url }}/gpgkey"
nvidia_docker_wrapper_url: https://raw.githubusercontent.com/NVIDIA/nvidia-docker/master/nvidia-docker
nvidia_docker_add_repo: true